name: Infra - build and test

on:
  push:
    paths:
      - "infra/**"
      - ".github/workflows/build-infra.yml"

permissions: {}

jobs:
  build-and-test-infra:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        shell: bash
        working-directory: infra

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3
        with:
          version: 10

      - name: Use Node.js 24.x
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24.x
          cache: pnpm
          cache-dependency-path: |
            infra/pnpm-lock.yaml

      - name: Install infra dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run eslint

      - name: Code style
        run: pnpm run prettier

      - name: Test infra
        run: pnpm run test
