name: Java - build and test

on:
  push:
    paths:
      - "java/**"
      - ".github/workflows/build-java.yml"

permissions: {}

jobs:
  build-and-test-java:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        shell: bash
        working-directory: java

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up JDK 25
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: 25
          distribution: "corretto"
          cache: "maven"

      - name: Build and test / Maven
        run: mvn -B clean package

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0

      - name: Build and test / Gradle
        run: |
          ./gradlew build
