name: Infra - update almost all dependencies

on:
  workflow_dispatch:

permissions: {}

jobs:
  update-infra-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    timeout-minutes: 4
    defaults:
      run:
        shell: bash
        working-directory: infra

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@26f6d4f2c533a43e6b5da0b4a5dd983f98f7b49a # v6.0.4
        with:
          version: 10

      - name: Use Node.js 24.x
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24.x
          cache: pnpm
          cache-dependency-path: |
            infra/pnpm-lock.yaml

      - name: Install infra dependencies
        run: pnpm install

      - name: Create working branch
        run: |
          git checkout -b infra-deps

      - name: Update dependencies
        run: |
          pnpm run npm-check-updates -u --reject @types/node --install never

      - name: Install updated infra dependencies
        run: pnpm install

      - name: Test
        run: |
          pnpm run test

      - name: Commit changes
        run: |
          git config --local user.email "pelaakso@users.noreply.github.com"
          git config --local user.name "pelaakso"
          git commit -a -m "Deps/infra: update infra dependencies"

      - name: Push changes
        run: |
          git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" infra-deps
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request
        run: |
          gh pr create --base main --head infra-deps --title "Deps/infra: update infra dependencies" --body "Update all dependencies, exluding node types"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
